apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lurus-system

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/hanmahong5-arch/lurus-api
    newTag: latest
