apiVersion: v1
kind: Service
metadata:
  name: lurus-api
  namespace: lurus-system
  labels:
    app: lurus-api
    app.kubernetes.io/name: lurus-api
    app.kubernetes.io/part-of: lurus
spec:
  selector:
    app: lurus-api
  ports:
    - name: http
      port: 8850
      targetPort: 3000
  type: ClusterIP
